### ISSUE TITLE
Debian package issues "The package is of bad quality" on Ubuntu 14.04

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cztomczak/cefpython#147]
```
When opening .deb file in Ubuntu Software center this message appears. THere 
are two buttons "OK" and "Ignore and install". After clicking details some logs 
appear:

    Lintian check results for /home/czarek/Downloads/python-cefpython3_31.1-1_amd64.deb:
    E: python-cefpython3: control-file-has-bad-owner md5sums czarek/czarek != root/root

    E: python-cefpython3: control-file-has-bad-owner postinst czarek/czarek != root/root

    E: python-cefpython3: control-file-has-bad-owner preinst czarek/czarek != root/root

    E: python-cefpython3: control-file-has-bad-owner prerm czarek/czarek != root/root

    E: python-cefpython3: wrong-file-owner-uid-or-gid python-cefpython3_31.1-1_amd64.deb 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/ 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/ 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/doc/ 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/doc/python-cefpython3/ 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/doc/python-cefpython3/changelog.Debian.gz 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/doc/python-cefpython3/copyright 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/ 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3-31.1.egg-info/ 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3-31.1.egg-info/PKG-INFO 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3-31.1.egg-info/SOURCES.txt 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3-31.1.egg-info/dependency_links.txt 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3-31.1.egg-info/top_level.txt 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/ 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/LICENSE.txt 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/README.txt 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/__init__.py 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/cef.pak 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/cefclient 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/cefpython_py27.so 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/devtools_resources.pak 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/examples/ 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/examples/example.html 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/examples/kivy-select-boxes/ 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/examples/kivy-select-boxes/kivy-selectBox.css 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/examples/kivy-select-boxes/kivy-selectBox.js 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/examples/kivy-select-boxes/kivy-test.html 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/examples/kivy-select-boxes/readme.md 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/examples/kivy_.py 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/examples/prism.css 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/examples/prism.js 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/examples/pygtk_.py 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/examples/pyqt.py 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/examples/wx/ 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/examples/wx/back.png 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/examples/wx/forward.png 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/examples/wx/reload_page.png 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/examples/wx/sample1.html 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/examples/wx/sample1.py 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/examples/wx/sample2.py 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/examples/wx/sample3.py 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/examples/wxpython-response.py 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/examples/wxpython.html 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/examples/wxpython.py 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/libcef.so 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/libffmpegsumo.so 1000/1000

    E: python-cefpython3: wrong-file-owner-uid-or-gid usr/share/pyshared/cefpython3/locales/ 1000/1000


```

Original issue reported on code.google.com by `czarek.t...@gmail.com` on 3 Dec 2014 at 7:38
